# A default document search pipeline with a good embedding based Retriever
version: '1.3.0'
name: 'DenseDocSearch'

# All nodes that we need for our pipelines
components:
  - name: DocumentStore
    type: DeepsetCloudDocumentStore
  - name: Retriever
    type: EmbeddingRetriever
    params:
      document_store: DocumentStore
      embedding_model: sentence-transformers/multi-qa-mpnet-base-dot-v1
      model_format: sentence_transformers
      top_k: 20
  - name: FileTypeClassifier
    type: FileTypeClassifier
  - name: TextFileConverter
    type: TextConverter
  - name: PDFConverter
    type: PDFToTextConverter
  - name: Preprocessor
    type: PreProcessor
    params:
      # As we are using a dense retriever we recommend splitting to smaller documents
      split_by: word
      split_length: 250
      split_overlap: 30
      split_respect_sentence_boundary: True

# Sticking the nodes together to one query pipeline and one indexing pipeline
pipelines:
  - name: query
    nodes:
      - name: Retriever
        inputs: [Query]
  - name: indexing
    nodes:
      # Depending on the file type we use a Text or PDF converter
      - name: FileTypeClassifier
        inputs: [File]
      - name: TextFileConverter
        inputs: [FileTypeClassifier.output_1]
      - name: PDFConverter
        inputs: [FileTypeClassifier.output_2]
      - name: Preprocessor
        inputs: [TextFileConverter, PDFConverter]
      - name: Retriever
        inputs: [Preprocessor]
      - name: DocumentStore
        inputs: [Retriever]