#A default English QA pipeline with a good embedding based Retriever and a large Reader model
version: '1.3.0'
name: 'QA_en'

components:
  - name: DocumentStore
    type: DeepsetCloudDocumentStore
  - name: Retriever
    type: EmbeddingRetriever
    params:
      document_store: DocumentStore
      embedding_model: sentence-transformers/multi-qa-mpnet-base-dot-v1
      model_format: sentence_transformers
      pooling_strategy: cls_token
      top_k: 20
  - name: Reader
    type: FARMReader
    params:
      model_name_or_path: deepset/roberta-large-squad2
      context_window_size: 700
  - name: TextFileConverter
    type: TextConverter
  - name: Preprocessor
    type: PreProcessor
    params:
      split_by: word
      split_length: 250
      split_overlap: 50
      split_respect_sentence_boundary: True

pipelines:
  - name: query
    nodes:
      - name: Retriever
        inputs: [Query]
      - name: Reader
        inputs: [Retriever]
  - name: indexing
    nodes:
      - name: TextFileConverter
        inputs: [File]
      - name: Preprocessor
        inputs: [TextFileConverter]
      - name: Retriever
        inputs: [Preprocessor]
      - name: DocumentStore
        inputs: [Retriever]
