#A default German pipeline with EmbeddingRetriever and a German QA model
version: '1.3.0'
name: 'QA_de'

components:
  - name: DocumentStore
    type: DeepsetCloudDocumentStore
    params:
      similarity: cosine
  - name: Retriever
    type: EmbeddingRetriever
    params:
      document_store: DocumentStore
      embedding_model: sentence-transformers/paraphrase-multilingual-mpnet-base-v2
      model_format: sentence_transformers
      top_k: 20
  - name: Reader
    type: FARMReader
    params:
      model_name_or_path: deepset/gelectra-base-germanquad
      context_window_size: 700
  - name: TextFileConverter
    type: TextConverter
  - name: Preprocessor
    type: PreProcessor
    params:
      split_by: word
      split_length: 250
      split_overlap: 30
      split_respect_sentence_boundary: True

pipelines:
  - name: query
    nodes:
      - name: Retriever
        inputs: [Query]
      - name: Reader
        inputs: [Retriever]
  - name: indexing
    nodes:
      - name: TextFileConverter
        inputs: [File]
      - name: Preprocessor
        inputs: [TextFileConverter]
      - name: Retriever
        inputs: [Preprocessor]
      - name: DocumentStore
        inputs: [Retriever]
